<?php
/**
 * Макет страницы.
 * 
 * Этот файл является частью модуля "Авторизация в Панели управления".
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 * 
 * @var \Ge\View\LayoutView $this
 * @var string $content
 */

$this->registerAsset('sign');
?>
<!DOCTYPE HTML>
<html lang="<?= $this->getLang() ?>">
<head>
    <meta charset="<?= $this->getCharset() ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->head() ?>
</head>

<body>
    <?php $this->beginBody() ?>
    <div class="g-gradient"></div>
    <div id="g-bs-mask" class="g-bs-mask">
        <div class="g-bs-mask__wrap">
            <div class="g-bs-mask__loader"></div>
        </div>
    </div>
    <div id="g-container" class="g-container">
    <?= $content ?>
    </div>

    <?= $this->renderFrom('partials/footer') ?>
    <?php $this->endBody() ?>
</body>

</html>
