<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 *
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Sign in to Control Panel</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The module implements a mechanism for authentication and authorization of users to gain access to the functionality of the GePanel Control Panel.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Customizing module</a></li>
    </ul>
</article>