<?php
use Ge\Helper\Url;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style type="text/css">
      .ReadMsgBody {
          width: 100%;
          background-color: #ffffff;
      }
      .ExternalClass {
          width: 100%;
          background-color: #ffffff;
      }
      body {
          width: 100%;
          background-color: #f2f4f5;
          margin: 0;
          padding: 0;
          -webkit-text-size-adjust: none !important;
      }
      table {
          border-collapse: separate;
      }
      body,
      table {
        font-family: 'Roboto', Roboto, Arial, Helvetica, sans-serif;
        font-smoothing: antialiased;
        -moz-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        -webkit-font-smoothing: antialiased;
      }
      /* МОБИЛЬНЫЕ СТИЛИ */
      @media screen and (max-width: 525px) {
        /* ПОЗВОЛЯЕТ ТАБЛИЦАМ ПЛАВАТЬ */
        .wrapper {
          width: 100% !important;
          max-width: 100% !important;
        }
        /* РЕГУЛИРУЕТ МАКЕТ ИЗОБРАЖЕНИЯ ЛОГОТИПА */
        .logo img {
          margin: 0 auto !important;
        }
        /* ИСПОЛЬЗУЙТЕ ЭТИ КЛАССЫ, ЧТОБЫ СКРЫТЬ КОНТЕНТ НА МОБИЛЬНЫХ УСТРОЙСТВАХ */
        .mobile-hide {
          display: none !important;
        }
        .img-max {
          max-width: 100% !important;
          width: 100% !important;
          height: auto !important;
        }
        /* ПОЛНАЯ ШИРИНА ТАБЛИЦ */
        .responsive-table {
          width: 100% !important;
        }
        /* ПОЛЕЗНЫЕ КЛАССЫ ДЛЯ РЕГУЛИРОВКИ PADDING НА МОБИЛЬНЫХ УСТРОЙСТВАХ */
        .padding {
          padding: 0px 5% 0px 5% !important;
        }
        .padding-meta {
          padding: 30px 5% 0px 5% !important;
          text-align: center;
        }
        .no-padding {
          padding: 0 !important;
        }
        .section-padding {
          padding: 0px 15px 0px 15px !important;
        }
        /* НАСТРОЙКА КНОПОК НА МОБИЛЬНОМ УСТРОЙСТВЕ */
        .mobile-button-container {
          margin: 0 auto;
          width: 100% !important;
        }
        .mobile-button {
          padding: 15px !important;
          border: 0 !important;
          font-size: 16px !important;
          display: block !important;
        }
      }
      table,
      td,
      b,
      a,
      strong,
      p,
      div {
          font-family: 'Helvetica Neue', Arial, 'sans-serif';
      }
      td.content {
          font: 16px/22px 'Helvetica Neue', Arial, 'sans-serif';
          text-align: left;
          padding: 50px 40px 0px 40px;
          color: #555555;
      }
      a {
          color: #207245;
          text-decoration: none;
      }
      /* ИСПРАВЛЕНИЕ ЦЕНТРА ДЛЯ ANDROID */
      div[style*="margin: 16px 0;"] {
          margin: 0 !important;
      }
      a.fiverr-social-icon {
          display: inline-block;
          margin: 2px 5px;
      }
    </style>
</head>

<body style="margin: 0 !important; padding: 0 !important;">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <!-- РАЗДЕЛИТЕЛЬ -->
        <tr>
            <td width="100%" align="center" valign="top" bgcolor="#f2f4f5" height="20"></td>
        </tr>
          <tr>
              <td bgcolor="#f2f4f5" align="center" style="padding: 0px 15px 0px 15px;" class="section-padding">
                  <!--[if (gte mso 9)|(IE)]>
                  <table align="center" border="0" cellspacing="0" cellpadding="0" width="500">
                      <tr>
                          <td align="center" valign="top" width="600">
                  <![endif]-->
                  <table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;" class="responsive-table">
                      <tr>
                          <td>
                              <!-- ЗАГОЛОВОК И ЛОГО -->
                              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                      <td align="center" style="padding: 40px 40px 0px 40px;">
                                          <a href="<?= Url::home() ?>" target="_blank">
                                              <img src="<?= Ge::alias('@/theme', '/widgets/images/email/logo.png') ?>" width="100px" border="0" style="vertical-align: middle;">
                                          </a>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td align="center" style="font-size: 24px; color: #0e0e0f; line-height: 28px; vertical-align: top; text-align:center; padding: 35px 40px 0px 40px;">
<?php if ($validate === 'success'): ?>
                                      Вы совершили вход в аккаунт
<?php elseif ($validate === 'device'): ?>
                                      Вы пытаетесь войти в аккаунт с нового устройства
  
<?php elseif ($invalid === 'attemptLimitReached'): ?>
                                      Исчерпан лимит попыток входа в аккаунт
<?php else: ?>
                                      Вы пытаетесь войти в аккаунт
<?php endif ?>
                                      </td>
                                  </tr>
                                  <!-- ГРАНИЦА -->
                                  <tr>
                                      <td align="center" bgcolor="#ffffff" height="1" style="padding:40px 40px 5px;" valign="top" width="100%">
                                          <table cellpadding="0" cellspacing="0" width="100%">
                                              <tbody>
                                                  <tr><td style="border-top:1px solid #e4e4e4;"></td></tr>
                                              </tbody>
                                          </table>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td class="content" style="font-size: 16px/22px; text-align: left;color: #406367;padding: 40px 40px 0px 40px;">
                                          <span style="padding-bottom: 10px; font-size: 16px; line-height: 24px; ">
<?php if ($profile && $profile->name): ?>
                                              <p>Здравствуйте, <?= $profile->name?></p>
<?php endif ?>
<?php if ($validate === 'success'): ?>
                                              <p>Мы заметили, что вы совершили вход в ваш аккаунт <strong><?= $username ?></strong> и хотели убедиться, что это действительно вы:</p>
<?php elseif ($validate === 'device'): ?>
                                              <p>Мы заметили попытку входа в ваш аккаунт <strong><?= $username ?></strong> с нового устройства и хотели убедиться, что это действительно вы:</p>
<?php elseif ($invalid === 'attemptLimitReached'): ?>
                                              <p>Мы заметили попытки входа в ваш аккаунт <strong><?= $username ?></strong> и хотели убедиться, что это действительно вы:</p>
<?php else: ?>
                                              <p>Мы заметили новую попытку входа в ваш аккаунт <strong><?= $username ?></strong> и хотели убедиться, что это действительно вы:</p>
<?php endif ?>

                                              <!-- АВТОРИЗАЦИЯ НА УСТРОЙСТВЕ -->
                                              <p style="font-weight: 500">
                                                  <span style="color: #95979D; font-size: 14px;">Устройство</span><br>
                                                  <span style="color: #406367">
<?php if ($row = $device->define(true, true)): 
    if (empty($row[1]) && empty($row[2])):
        echo '<неизвестно>';
    else:
        echo $row[1] ?: '', $row[2] ? ($row[1] ? ', ' : '') . $row[2] : '';
    endif;
endif; ?>
                                                  </span>
                                              </p>
                                              <p style="font-weight: 500">
                                                  <span style="color: #95979D; font-size: 14px">Приблизительное местоположение</span><br>
                                                  <span style="color: #406367"><?= $row && $row[0] ? $row[0] . ', <местоположение неизвестно>' : '<неизвестно>' ?></span>
                                              </p>
                                              <p style="font-weight: 500">
                                                  <span style="color: #95979D; font-size: 14px">Дата и время</span><br>
                                                  <span style="color: #406367"><?= $date ?></span>
                                              </p>

<?php if ($validate === 'device' && ($row = $device->find(true))): ?>
                                              <!-- АВТОРИЗАЦИЯ НА УСТРОЙСТВЕ РАНЕЕ -->
                                              <p style="margin-bottom: -15px;">Ранее, вход в аккаунт <strong><?= $username ?></strong> был выполнен с устройства: </p>
                                              <table border="0">
                                                  <tr>
                                                      <td style="background:none; height:20px;"> </td>
                                                  </tr>
                                              </table>
                                              <table border="0" cellpadding="0" cellspacing="0" style="font-size: 15px; line-height: 22px; color: #155724; font-weight: 500; border: 1px solid #e5f0e7; border-radius: 3px; background-color: #f1fff5; width: 100%">
                                                  <tr>
                                                      <td colspan="3" height="24"> </td>
                                                  </tr>
                                                  <tr>
                                                      <td width="24"> </td>
                                                      <td align="left">
                                                          <p style="font-weight: 500">
                                                              <span style="color: #95979D; font-size: 14px;">Устройство</span><br>
                                                              <span style="color: #222325">
<?php 
    if (empty($row[1]) && empty($row[2])):
        echo '<неизвестно>';
    else:
        echo $row[1] ?: '', $row[2] ? ($row[1] ? ', ' : '') . $row[2] : '';
    endif;
?>
                                                              </span>
                                                          </p>
                                                          <p style="font-weight: 500">
                                                              <span style="color: #95979D; font-size: 14px">Приблизительное местоположение</span><br>
                                                              <span style="color: #222325"><?= $row && $row[0] ? $row[0] . ', <местоположение неизвестно>' : '<неизвестно>' ?></span>
                                                          </p>
                                                          <p style="font-weight: 500">
                                                              <span style="color: #95979D; font-size: 14px">Дата и время</span><br>
                                                              <span style="color: #222325"><?= $visitedDate ?></span>
                                                          </p>
                                                      </td>
                                                      <td width="24"> </td>
                                                  </tr>
                                                  <tr>
                                                      <td colspan="3" height="24"> </td>
                                                  </tr>
                                              </table>
                                              <table border="0">
                                                  <tr>
                                                      <td style="background:none; height:20px;"> </td>
                                                  </tr>
                                              </table>
<?php endif ?>
                                              <p style="font-size: 14px; line-height: 22px">
<?php if ($validate === 'success'): ?>
                                              Если не вы вошли в систему, мы рекомендуем вам изменить пароль как можно скорее, чтобы защитить свой аккаунт. 
                                              При изменении пароля все устройства, на которых выполнен вход в ваш аккаунт, будут отключены.
<?php elseif ($validate === 'device'): ?>
                                              Если вы не пытались войти в систему с нового устройства в последнее время, мы рекомендуем вам изменить пароль как можно скорее, чтобы защитить свой аккаунт. При изменении пароля все устройства, на которых выполнен вход в ваш аккаунт, будут отключены.
<?php else: ?>
                                              Если вы не пытались войти в систему в последнее время, мы рекомендуем вам изменить пароль как можно скорее, чтобы защитить свой аккаунт. При изменении пароля все устройства, на которых выполнен вход в ваш аккаунт, будут отключены.
<?php endif ?>
                                              </p>
                                              <table border="0">
                                                  <tr>
                                                      <td style="background:none; height:20px;"> </td>
                                                  </tr>
                                              </table>
                                              <table border="0" cellpadding="0" cellspacing="0" style="font-size: 14px; line-height: 22px; color: #856404; font-weight: 500; border: 1px solid #ffeeba; border-radius: 3px; background-color: #fff3cd;">
                                                  <tr>
                                                      <td colspan="3" height="24"> </td>
                                                  </tr>
                                                  <tr>
                                                      <td width="24"> </td>
                                                      <td align="left">
                                                          <p>Если вы не желаете больше получать уведомления, обратитесь к администратору.</p>
                                                      </td>
                                                      <td width="24"> </td>
                                                  </tr>
                                                  <tr>
                                                      <td colspan="3" height="24"> </td>
                                                  </tr>
                                              </table>
                                              <table border="0">
                                                  <tr>
                                                      <td style="background:none; height:20px;"> </td>
                                                  </tr>
                                              </table>
                                              <p>С уважением,<br><b><?= $version->name ?></b></p>
                                          </span>
                                      </td>
                                  </tr>
                              </table>
                          </td>
                      </tr>
                      <!-- РАЗДЕЛИТЕЛЬ -->
                      <tr>
                          <td width="100%" align="center" valign="top" bgcolor="#ffffff" height="45"></td>
                      </tr>
                  </table>
                  <!--[if (gte mso 9)|(IE)]>
                          </td>
                      </tr>
                  </table>
                  <![endif]-->
              </td>
          </tr>
          <tr>
              <td bgcolor="#f2f4f5" align="center" style="padding: 20px 0px;">
                  <!--[if (gte mso 9)|(IE)]>
                  <table align="center" border="0" cellspacing="0" cellpadding="0" width="500">
                      <tr>
                          <td align="center" valign="top" width="500">
                  <![endif]-->
                  <!-- СОЦСЕТИ -->
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="max-width: 600px;" class="responsive-table">
                      <tr> </tr>
                      <tr>
                          <td bgcolor="#f2f4f5" align="center">
                              <!--[if (gte mso 9)|(IE)]>
                              <table align="center" border="0" cellspacing="0" cellpadding="0" width="500">
                                  <tr>
                                    <td align="center" valign="top" width="500">
                              <![endif]-->
                              <!-- СОЦСЕТИ -->
                              <?php //  Url::brandName() заменить на название своей компании ?>
                              <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="max-width: 600px;" class="responsive-table">
                                  <tr>
                                      <td align="center" class="center" style="text-align: center; padding:10px 10px 10px 10px;">
                                          <!--Twitter-->
                                          <a href="https://twitter.com/<?= Url::brandName() ?>" style="display: inline-block; margin: 2px">
                                              <img height="40" src="<?= Ge::alias('@/theme', '/widgets/images/email/twitter.png') ?>" width="40">
                                          </a>
                                          <!--Facebook-->
                                          <a href="https://www.facebook.com/<?= Url::brandName() ?>" style="display: inline-block; margin: 2px">
                                              <img height="40" src="<?= Ge::alias('@/theme', '/widgets/images/email/facebook.png') ?>" width="40">
                                          </a>
                                          <!--LinkedIn-->
                                          <a href="https://www.linkedin.com/company/<?= Url::brandName() ?>" style="display: inline-block; margin: 2px">
                                              <img height="40" src="<?= Ge::alias('@/theme', '/widgets/images/email/linkedin.png') ?>" width="40">
                                          </a>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td style="color: #999999 ;font-size: 12px;line-height: 16px;text-align: center;">
<?php if ($profile && $profile->name): ?>
                                      Это письмо было предназначено для <?= $profile->name ?> потому,<br> что вы пользуютесь <?= $version->name ?>.
<?php else: ?>
                                      Это письмо было отправлено в качестве уведомления, <br>так как вы пользуютесь <?= $version->name ?>.
<?php endif // profile ?>             | <span>
                                          Страница авторизации <a target="_blank" href="<?= Url::toBackend() ?>"><?= Url::toBackend() ?></a>.
                                          <br>
                                          <a style="font-size: 14px;line-height: 25px;" target="_blank" href="<?= Url::home() ?>"><?= $version->getReleaseName(true) ?></a>
                                        </span>
                                      </td>
                                  </tr>
                              </table>
                              <!--[if (gte mso 9)|(IE)]>
                                      </td>
                                  </tr>
                              </table>
                              <![endif]-->
                          </td>
                      </tr>
                  </table>
                  <!--[if (gte mso 9)|(IE)]>
                          </td>
                      </tr>
                  </table>
                  <![endif]-->
              </td>
          </tr>
    </table>
</body>

</html>
